language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: [hhvm, hhvm-nightly]
    fast_finish: true

before_script:
    - composer install --prefer-source
    - touch files/salemapp.test.sqlite
    - chmod a+w files/salemapp.test.sqlite

script: phpunit --coverage-text

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ebaba92b4cc7bca39419
    on_success: always
    on_failure: always
    on_start: false
